spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda
spring.datasource.username=postgres
spring.datasource.password=2302
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true